'use client';

import { useState } from 'react';
import { Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function PrintDeliveryButton({ deliveryId, userName }) {
  const [loading, setLoading] = useState(false);

  const handlePrint = async () => {
    setLoading(true);
    try {
      // Fetch full delivery details including items
      const response = await fetch(`/api/inventory/deliveries/${deliveryId}`);
      if (!response.ok) throw new Error('Failed to fetch delivery details');
      const delivery = await response.json();

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.text('StockMaster Delivery Note', 105, 15, { align: 'center' });
      
      doc.setFontSize(10);
      doc.text(`Generated by: ${userName || 'Unknown'}`, 105, 22, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleString()}`, 105, 27, { align: 'center' });

      // Delivery Details
      doc.setFontSize(12);
      doc.text(`Delivery ID: #${delivery.delivery_id}`, 14, 40);
      doc.text(`Customer: ${delivery.customer_name}`, 14, 46);
      doc.text(`Status: ${delivery.status.toUpperCase()}`, 14, 52);
      doc.text(`Created Date: ${new Date(delivery.created_at).toLocaleDateString()}`, 14, 58);
      if (delivery.sequence_number) {
         doc.text(`Ref No: ${delivery.sequence_number}`, 150, 40);
      }

      // Items Table
      const tableColumn = ["Product", "SKU", "Warehouse", "Quantity"];
      const tableRows = delivery.items.map(item => [
        item.product_name,
        item.sku,
        item.warehouse_name,
        item.quantity
      ]);

      autoTable(doc, {
        startY: 65,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235] }, // Blue color
      });

      // Footer
      const finalY = doc.lastAutoTable.finalY || 65;
      doc.setFontSize(10);
      doc.text('Thank you for your business.', 105, finalY + 20, { align: 'center' });

      doc.save(`delivery_${delivery.delivery_id}.pdf`);
    } catch (error) {
      console.error('Print failed:', error);
      alert('Failed to generate PDF');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handlePrint}
      disabled={loading}
      className="p-2 text-slate-600 hover:text-slate-900 transition-colors flex items-center gap-2 "
      title="Print Delivery Note"
    >
      <Printer className={`h-4 w-4 ${loading ? 'animate-pulse' : ''}`} />
      Print
    </button>
  );
}
