'use client';

import { useState } from 'react';
import { Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function PrintReceiptButton({ receiptId, userName }) {
  const [loading, setLoading] = useState(false);

  const handlePrint = async () => {
    setLoading(true);
    try {
      // Fetch full receipt details including items
      const response = await fetch(`/api/inventory/receipts/${receiptId}`);
      if (!response.ok) throw new Error('Failed to fetch receipt details');
      const receipt = await response.json();

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.text('StockMaster Receipt', 105, 15, { align: 'center' });
      
      doc.setFontSize(10);
      doc.text(`Generated by: ${userName || 'Unknown'}`, 105, 22, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleString()}`, 105, 27, { align: 'center' });

      // Receipt Details
      doc.setFontSize(12);
      doc.text(`Receipt ID: #${receipt.receipt_id}`, 14, 40);
      doc.text(`Supplier: ${receipt.supplier_name}`, 14, 46);
      doc.text(`Status: ${receipt.status.toUpperCase()}`, 14, 52);
      doc.text(`Created Date: ${new Date(receipt.created_at).toLocaleDateString()}`, 14, 58);
      if (receipt.sequence_number) {
         doc.text(`Ref No: ${receipt.sequence_number}`, 150, 40);
      }

      // Items Table
      const tableColumn = ["Product", "SKU", "Warehouse", "Quantity"];
      const tableRows = receipt.items.map(item => [
        item.product_name,
        item.sku,
        item.warehouse_name,
        item.quantity
      ]);

      autoTable(doc, {
        startY: 65,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [22, 163, 74] }, // Green color
      });

      // Footer
      const finalY = doc.lastAutoTable.finalY || 65;
      doc.setFontSize(10);
      doc.text('Thank you for your business.', 105, finalY + 20, { align: 'center' });

      doc.save(`receipt_${receipt.receipt_id}.pdf`);
    } catch (error) {
      console.error('Print failed:', error);
      alert('Failed to generate PDF');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handlePrint}
      disabled={loading}
      className="p-2 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100 transition-colors"
      title="Print Receipt"
    >
      <Printer className={`h-4 w-4 ${loading ? 'animate-pulse' : ''}`} />
    </button>
  );
}
